### ISSUE TITLE
Crashing at a fixed date 

### ISSUE THREAD

**Issue by jigsaw717** [cray935/stellaris-mods#3]
[error.log](https://github.com/cray935/stellaris-mods/files/1818418/error.log)

**Comment by cray935** [comment]
Can you please attach the Stellaris/logs/error.log file? I cannot use memory dumps. If there is an issue with my mod, it will be logged in the files.

**Comment by jigsaw717** [comment]
my bad, never done this before, updated my original comment with the correct file. Hope it helps

**Comment by cray935** [comment]
So I read the error log and it seems your game is heavy instable because of some mods which overhaul mechanics and have some conflicts. I did not find a single error of the life engineering mod.

Sorry that I cannot help you further with the issue :( But thank you for the effort.
